title: "Digital Credentials"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
aux_links:
  "Edit on GitHub":
    - "https://github.com/cloudtnt-rcl/RCL.CloudTnT.Express.Installation"
callouts:
  information:
    title: Information
    color: blue
  warning:
    title: Warning
    color: red